== rkt RPM

This source tree provides the means to create an RPM from the source tree of the
rkt implementation of the Application Container Specification.

The goal is to make rkt available as an installable package for any
distribution which uses RPM as the binary distribution mechanism.

A further goal is to get the packaging files incorporated into the
upstream source tree for the rkt process so that packaging is
considered a first-class part of the development and build process.

== Package Files

The rkt package will consist of three (3) binary files and a set of
supporting files and directories.  The placement of the files will be
consistent with the
https://fedoraproject.org/wiki/Packaging:Guidelines[Fedora Packaging
Guidelines].

```
/usr/bin/rkt
/usr/lib/systemd/system/rkt-metadata.service
/usr/libexec/rkt/stage1.aci
/usr/share/doc/rkt/*
/var/lib/rkt
/var/lib/rkt/cas
/var/lib/rkt/cas/db
/var/lib/rkt/tmp
/var/lib/rkt/containers
```

=== Executable files: `rkt`

- `rkt`: The rkt CLI tool - retrive and run containers

This is the CLI tool which is used to retrieve images and execute
containers. It provides commands for fetching, examining and
controlling containers as well as cleanup and initialization.

=== Service Control Files

- rkt-metadata.service

rkt containers which require a private network must get their
network information from the rkt *metadata* service. The network is
established by the `rkt` binary and the network plugins and so is
unknown by the user at invocation.

The rkt metadata service provides a way for the rkt startup
process to provide the network information (and other potentially
sensitive information) to the container.

The rkt metadata service can be started and monitored by
`systemd`. The `rkt-metadata.service` file adds the controls for
the metadata service to the systemd repository.

NOTE: 27-Mar-2015 - service files for the metadata pipe and the metadata service
have been included upstream - ML: 

https://github.com/coreos/rkt/pull/674[add system service and
socket files]

=== The Stage1 Image: `stage1.aci`

The stage1 image is an Application Container Specification compliant
image file.  It contains the intermediate framework and the tools
necessary to set up the pre-start environment for a new container.
Some of the contents are compiled as part of the rkt build
process.  Others are standard OS startup files (systemd).  These are
currently extracted from a stock CoreOS bootable image, but they could
be built from source or pulled from other packages depending on the
distribution they are pulled from.

The build process includes a switch which disables downloading the the
CoreOS image to provide the _systemd_ files in `/usr`:

    RKT_STAGE1_USR_FROM=src

When alternate methods of retrieving or producing these files is
added, it should extend the existing mecanisms.

The `stage1.img` file is used by the `rkt` binary when a new container
is run.  It can be replaced at the invocation using the
`--stage1-image` option.

The stage1 image is expected to be in the same directory as the `rkt`
binary.  For packaging, the location of the stage1 image should be
expanded to a search path.  This would allow distributions with
specifications for the locations of extra binaries to conform.

For RPM based packaging, the default stage1 image should reside in
`/usr/libexec/rkt/stage1.img`.

=== Runtime Storage and Database

rkt retrieves and unpacks Application Container images, and
instantiates containers on behalf of users.  The container image files
and the containers themselves must have a place on the host
filesystem.

The runtime storage and control databases reside in
`/var/lib/rkt`. The directories are created and ownership and
permission set when the package is installed.

== rkt Group, Ownership and Permissions

Currently the enabling technology for rkt, _nsenter_ requires root
privileges. However, a number of precursor operations, such as
management of image files and pre-run or post-run containers, do not
require root.

Non-root operations can be enabled by creating a _rkt_ group (in
`/etc/group`) and setting the group ownership and permissions of the
directories in `/var/lib/rkt` so that members of the rkt group
have access.

The rkt package should create the _rkt_ group if it is not
present at installation, and the package installation should set the
group and permissions of the storage and database directories to
enable non-root operations.

== Sources

The rkt RPM will be built entirely from upstream sources. Any
auxilliary files will be tracked here with the goal of getting them
accepted upstream.

=== rkt Binary Sources

The rkt sources will be retrieved from the Github repository at or
just prior to package build time. If they are retrieved prior to
build, they will be collected in a gzipped tar archive for holding.

=== Stage1 Image Sources

The rkt deliverable requires a *stage1 image* which is the template
used to create the namespaces which will contain the image processes.

Currently the stage1 image is created using elements pulled from a
CoreOS run-time image.  This runtime image is retrieved and then
cached but it is treated as a binary "blob" whos provinence cannot be
traced.

For RPM packaging, the `/usr` contents of the stage1 image will be extracted
from well known RPMs.

If a new source for these files is added, it should be controlled with the existing build switch: `RKT_STAGE1_USR_FROM=(src|??)` .

It is possible that, in the future, the stage1 image build process will be made
distinct from the rkt binary build process. In that case it may be
made a separate dependent package

== References

- rkt Source Tree
    https://github.com/coreos/rkt
- Application Container Specification
    https://github.com/appc/spec
